# os: linux and sudo: false is assumed, which means it is using container-based Ubuntu 12.04
language: python
cache: pip
# build matrix: different python and pandoc versions
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  # - "3.6-dev" # 3.6 development branch
  # - "3.7-dev" # 3.7 development branch
  # - "nightly" # currently points to 3.7-dev
  # pypy (version info from [Changelogs — PyPy documentation](http://doc.pypy.org/en/latest/index-of-whatsnew.html))
  # - "pypy"  # PyPy2.7 5.3.1 (CPython 2.7 compatible)
  # - "pypy3" # PyPy3 2.4.0 (CPython 3.2 compatible)
# https://groups.google.com/forum/?fromgroups#!topic/pandoc-discuss/uGASAhRydfI
env:
  - pandocVersion=1.19.2.4
  - pandocVersion=latest
matrix:
  allow_failures:
    # - python: "3.6-dev"
    # - python: "3.7-dev"
    # - python: "nightly"
    # - python: "pypy3"
  fast_finish: true
# download pandoc
before_install:
  - |
    if [[ $pandocVersion == "latest" ]]; then
      url="https://github.com/jgm/pandoc/releases/latest"
    else
      url="https://github.com/jgm/pandoc/releases/tag/$pandocVersion"
    fi
    path=$(curl -L $url | grep -o '/jgm/pandoc/releases/download/.*-amd64\.deb')
    downloadUrl="https://github.com$path"
    file=${path##*/}
# install dependencies
install:
  # pandoc
  - wget $downloadUrl &&
    sudo dpkg -i $file
  # latest pip dropped support for py3.2, which is the version of python in pypy3
  - if [[ "$TRAVIS_PYTHON_VERSION" != "pypy3" ]]; then pip install -U pip; fi
  - pip install -r requirements.txt
before_script:
  # pasteurize for py2 only, except setup.py & panflute/version.py
  - |
    if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" || "$TRAVIS_PYTHON_VERSION" == "pypy" ]]; then
      mv setup.py setup.py.temp
      mv panflute/version.py panflute/version.py.temp
      pasteurize -wnj 4 .
      mv setup.py.temp setup.py
      mv panflute/version.py.temp panflute/version.py
    fi
# commands to run tests
script:
  - pytest
